version: '3'  # Docker Compose file version (version 3 is a commonly used format)

services:
  # Zookeeper service (required by Kafka for managing broker metadata)
  zookeeper:
    image: wurstmeister/zookeeper  # Zookeeper image from the wurstmeister repository
    ports:
      - "2181:2181"  # Expose Zookeeper's default port 2181 to the host machine
    networks:
      - my_custom_network  # Attach the Zookeeper container to the custom network

  # Kafka service
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    networks:
      - my_custom_network


# Custom network configuration
networks:
  my_custom_network:
    driver: bridge  # Use Docker's default bridge driver for internal networking between services